name: C/C++ CI

on: [push]
  #pull_request:
    #branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi cmake gdb-multiarch qemu-system-arm
    - name: configure
      run: cmake --preset arm-cortex-m0-unix
    - name: build
      run: cmake --build --preset arm-cortex-m0-unixcmake --build --preset arm-cortex-m0-unix